sudo: required
language: generic

services:
  - docker

before_install:
  - docker build -t harisht847/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run -e CI=true harisht847/react-test npm test

after_success:
  - docker build -t harisht847/multi-client ./client
  - docker build -t harisht847/multi-nginx ./nginx
  - docker build -t harisht847/multi-server ./server
  - docker build -t harisht847/multi-worker ./worker
  # Log in to the docker CLI
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  # Take those images and push them to docker hub
  - docker push harisht847/multi-client
  - docker push harisht847/multi-nginx
  - docker push harisht847/multi-server
  - docker push harisht847/multi-worker

deploy:
  provider: elasticbeanstalk
  region:  "ap-south-1"  
  app: "multi-docker"
  env: "MultiDocker-env"
  bucket_name: "elasticbeanstalk-ap-south-1-209909805642"
  bucket_path: "docker-multi"
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY

